# FROM hub.c.163.com/public/ubuntu:14.04
FROM ubuntu:18.04
COPY freenet.tmp /fred
# COPY start.sh /start.sh
COPY sources.list /etc/apt/sources.list
RUN mkdir /root/.pip
COPY pip.conf /root/.pip/
RUN apt update && apt install -y openjdk-8-jre\
                                 vim\
                                 w3m\
                                 haveged\
                                 rng-tools\
                                 fish\
                                 python3\
                                 python3-pip\
                                 tcpdump\
                                 net-tools\
                                 iputils-ping
RUN pip3 install ipython3 pyfreenet==0.4.1 scapy
RUN adduser --disabled-password tester
RUN chown -R tester:tester /fred

RUN apt install -y iproute2 iputils-arping net-tools tcpdump curl telnet iputils-tracepath traceroute
RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump
ENTRYPOINT /usr/sbin/sshd -D
